name: Build
on:
  push:
    branches:
      - main

jobs:
  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: main
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: see directory
        run: ls
